'use client';
import {useState,type FormEvent} from 'react';
import {useAuth} from './auth-gate';
import {supabase} from '@/lib/supabase-browser';
import {Button} from '@/components/ui/button';
import {AppearanceControl} from './appearance';

export default function ProfileView({refresh}:{refresh:()=>Promise<unknown>}){
 const {user}=useAuth();
 const [name,setName]=useState(String(user.user_metadata?.name||user.user_metadata?.full_name||'')),[bio,setBio]=useState(String(user.user_metadata?.bio||'')),[email,setEmail]=useState(user.email||''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[nonce,setNonce]=useState(''),[needNonce,setNeedNonce]=useState(false),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState('');
 async function run(kind:string,action:()=>Promise<string>){if(busy)return;setBusy(kind);setError('');setNotice('');try{setNotice(await action())}catch(e){setError((e as Error).message||'Perubahan belum tersimpan.')}finally{setBusy('')}}
 async function profile(e:FormEvent){e.preventDefault();await run('profile',async()=>{const clean=name.trim();if(!clean)throw new Error('Nama tidak boleh kosong.');const {error}=await supabase().auth.updateUser({data:{name:clean,full_name:clean,bio:bio.trim()}});if(error)throw error;try{await refresh()}catch{return 'Profil tersimpan. Muat ulang halaman untuk memperbarui nama di semua bagian.'}return 'Profil berhasil disimpan.'})}
 async function changeEmail(e:FormEvent){e.preventDefault();await run('email',async()=>{const next=email.trim();if(next===user.email)throw new Error('Email baru masih sama.');const {data,error}=await supabase().auth.updateUser({email:next},{emailRedirectTo:location.origin});if(error)throw error;return data.user?.email===next?'Email berhasil diperbarui.':'Permintaan perubahan email dikirim. Periksa email lama dan baru untuk tautan konfirmasi. Email login tetap yang lama sampai perubahan selesai.'})}
 async function changePassword(e:FormEvent){e.preventDefault();await run('password',async()=>{if(password!==confirm)throw new Error('Konfirmasi password belum sama.');const {error}=await supabase().auth.updateUser({password,...(needNonce?{nonce:nonce.trim()}:{})});if(error){if(error.code==='reauthentication_needed'||error.message.toLowerCase().includes('reauthentication')){setNeedNonce(true);throw new Error('Verifikasi ulang diperlukan. Klik Kirim kode verifikasi, lalu masukkan kode dari email.')}throw error;}setPassword('');setConfirm('');setNonce('');setNeedNonce(false);return 'Password berhasil diperbarui.'})}
 return <section className="profile-view"><div className="profile-intro"><span className="profile-large-avatar">{(name.trim()||user.email||'A').slice(0,1).toUpperCase()}</span><div><h2>Profil akunmu</h2><p>{user.email}</p><small>Perubahan profil berlaku untuk akun ini di semua ruang.</small></div></div>{notice&&<p className="auth-success profile-message" role="status">{notice}</p>}{error&&<p className="auth-error profile-message" role="alert">{error}</p>}<div className="two-grid"><section className="panel account-panel"><h3>Informasi pribadi</h3><form onSubmit={profile}><fieldset disabled={!!busy}><label>Nama tampilan<input required maxLength={80} autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label><label>Bio singkat<textarea maxLength={280} rows={3} value={bio} onChange={e=>setBio(e.target.value)} placeholder="Tentang dirimu atau tujuanmu"/></label><small>{bio.length}/280 karakter</small><Button type="submit">{busy==='profile'?'Menyimpan…':'Simpan profil'}</Button></fieldset></form><h3>Tampilan</h3><AppearanceControl/><p className="hint">Tema tersimpan di browser ini.</p></section><section className="panel account-panel"><h3>Email login</h3><p>Email saat ini: {user.email}</p>{user.new_email&&<p className="hint">Menunggu konfirmasi: {user.new_email}</p>}<form onSubmit={changeEmail}><fieldset disabled={!!busy}><label>Email baru<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><Button type="submit" variant="outline">{busy==='email'?'Mengirim…':'Ubah email'}</Button></fieldset></form><h3>Ubah password</h3><form onSubmit={changePassword}><fieldset disabled={!!busy}><label>Password baru<input required minLength={8} maxLength={128} type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Ulangi password baru<input required minLength={8} maxLength={128} type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>{needNonce&&<><Button type="button" variant="outline" onClick={()=>run('nonce',async()=>{const {error}=await supabase().auth.reauthenticate();if(error)throw error;return 'Kode verifikasi dikirim. Periksa email akunmu.'})}>Kirim kode verifikasi</Button><label>Kode verifikasi<input required autoComplete="one-time-code" value={nonce} onChange={e=>setNonce(e.target.value)}/></label></>}<Button type="submit">{busy==='password'?'Menyimpan…':'Simpan password'}</Button></fieldset></form></section></div></section>;
}
