export type Tx={id:string;date:string;description:string;type:string;amount:number;category:string;account:string;projectId:string;fingerprint?:string;source?:string;recordedAt?:string};
export type Project={id:string;name:string;revenue:number;cost:number;probability:number;status:string;deadline:string;note:string};
export type Event={id:string;title:string;date:string;time:string;reminder:number;note:string;done:boolean};
export type Settings={target:number;targetDate:string;birthDate:string;openingBalance:number;openingDate:string;assets:number;liabilities:number;configured:boolean};
export type Data={transactions:Tx[];projects:Project[];events:Event[];settings:Settings};
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const empty=():Data=>({transactions:[],projects:[],events:[],settings:{target:500e9,targetDate:'2065-12-31',birthDate:'2007-11-24',openingBalance:0,openingDate:today().slice(0,4)+'-01-01',assets:0,liabilities:0,configured:false}});
export const money=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
export const short=(n:number)=>{const a=Math.abs(n),v=a>=1e12?[n/1e12,'T']:a>=1e9?[n/1e9,'M']:a>=1e6?[n/1e6,'jt']:a>=1e3?[n/1e3,'rb']:[n,''];return Number(v[0]).toLocaleString('id-ID',{maximumFractionDigits:1})+' '+v[1]};
export const day=(s:string,full=false)=>new Date(s+'T12:00:00Z').toLocaleDateString('id-ID',{day:'numeric',month:full?'long':'short',...(full?{year:'numeric'}:{})});
export const offset=(s:string,n:number)=>{const d=new Date(s+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
export const validDate=(s:string)=>/^\d{4}-\d{2}-\d{2}$/.test(s)&&!isNaN(Date.parse(s))&&new Date(s+'T12:00:00Z').toISOString().slice(0,10)===s;
export const types:Record<string,string>={income:'Pemasukan',expense:'Pengeluaran',transfer:'Transfer internal','capital-in':'Dana masuk nonpendapatan','capital-out':'Dana keluar nonbiaya'};
export const statuses:Record<string,string>={draft:'Draft',negotiation:'Negosiasi',won:'Berhasil',done:'Selesai',lost:'Batal'};
export const categories=['Proyek & usaha','Gaji','Makan & minum','Transportasi','Belanja','Pendidikan','Tagihan','Keluarga','Kesehatan','Hiburan','Investasi','Biaya bank','Transfer internal','Lainnya'];
export const delta=(t:Tx)=>['income','capital-in'].includes(t.type)?t.amount:['expense','capital-out'].includes(t.type)?-t.amount:0;
export const cash=(d:Data,at=today())=>d.settings.openingBalance+d.transactions.filter(t=>t.date>=d.settings.openingDate&&t.date<=at).reduce((s,t)=>s+delta(t),0);
export const wealth=(d:Data)=>cash(d)+d.settings.assets-d.settings.liabilities;
export const totals=(ts:Tx[])=>{const income=ts.filter(t=>t.type==='income').reduce((s,t)=>s+t.amount,0),expense=ts.filter(t=>t.type==='expense').reduce((s,t)=>s+t.amount,0);return {income,expense,surplus:income-expense,rate:income?(income-expense)/income*100:null}};
export const remaining=(p:Project,d:Data)=>p.revenue-p.cost-totals(d.transactions.filter(t=>t.projectId===p.id&&t.date<=today())).surplus;
export const active=(d:Data)=>d.projects.filter(p=>['draft','negotiation','won'].includes(p.status));
export const potential=(d:Data)=>active(d).reduce((s,p)=>s+remaining(p,d),0);
export const range=(period:string,month:string,now=today())=>({start:period==='today'?now:period==='7d'?offset(now,-6):period==='30d'?offset(now,-29):period==='month'?month+'-01':now.slice(0,4)+'-01-01',end:period==='month'?new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5)),0,12)).toISOString().slice(0,10):now});
export function chartRows(d:Data,start:string,end:string){const monthly=(Date.parse(end)-Date.parse(start))/864e5>95,rows:Record<string,any>={};let value=cash(d,offset(start,-1));for(let s=start;s<=end;s=offset(s,1)){if(s===d.settings.openingDate)value=d.settings.openingBalance;const ts=d.transactions.filter(t=>t.date===s),t=totals(ts);if(s>=d.settings.openingDate)value+=ts.reduce((a,b)=>a+delta(b),0);const k=monthly?s.slice(0,7):s;rows[k]={label:monthly?new Date(s+'T12:00Z').toLocaleDateString('id-ID',{month:'short'}):day(s),balance:s>=d.settings.openingDate?value:null,income:(rows[k]?.income||0)+t.income,expense:(rows[k]?.expense||0)+t.expense};}return Object.values(rows)}
export function calendarFile(events:Event[]){const escape=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;'),utc=(d:Date)=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//ARAH//Agenda//ID','CALSCALE:GREGORIAN'];for(const e of events){const at=new Date(e.date+'T'+e.time+':00+07:00');lines.push('BEGIN:VEVENT','UID:'+e.id+'@arah','DTSTAMP:'+utc(new Date()),'DTSTART:'+utc(at),'DTEND:'+utc(new Date(+at+3600000)),'SUMMARY:'+escape(e.title),'DESCRIPTION:'+escape(e.note),'BEGIN:VALARM','ACTION:DISPLAY','DESCRIPTION:'+escape(e.title),'TRIGGER:-PT'+e.reminder+'M','END:VALARM','END:VEVENT')}lines.push('END:VCALENDAR');return lines.map(line=>{let out='',part='';for(const c of line){if(new TextEncoder().encode(part+c).length>72){out+=part+'\r\n ';part=''}part+=c}return out+part}).join('\r\n')+'\r\n'}
export function demoData():Data{const d=empty(),now=today(),start=offset(now,-29);d.settings={...d.settings,openingBalance:12500000,openingDate:start,assets:7500000,configured:true};const raw:[number,string,string,number,string][]=[[1,'Pembayaran proyek foto','income',5500000,'Proyek & usaha'],[3,'Belanja kebutuhan','expense',780000,'Belanja'],[5,'Transportasi','expense',230000,'Transportasi'],[8,'Komisi penjualan','income',3200000,'Proyek & usaha'],[11,'Makan & kopi','expense',325000,'Makan & minum'],[14,'Internet bulanan','expense',350000,'Tagihan'],[17,'Buku & kuliah','expense',650000,'Pendidikan'],[20,'Pembayaran desain','income',2500000,'Proyek & usaha'],[25,'Belanja bulanan','expense',620000,'Belanja'],[28,'Transportasi','expense',180000,'Transportasi']];d.transactions=raw.map((t,i)=>({id:'demo-'+i,date:offset(start,t[0]),description:t[1],type:t[2],amount:t[3],category:t[4],account:'BCA',projectId:''}));d.projects=[{id:'p1',name:'Distribusi sembako',revenue:48000000,cost:39500000,probability:70,status:'negotiation',deadline:offset(now,14),note:'Contoh proyek, bukan data pribadi.'},{id:'p2',name:'Produksi konten',revenue:6500000,cost:1700000,probability:100,status:'won',deadline:offset(now,7),note:''},{id:'p3',name:'Kolaborasi brand',revenue:12000000,cost:8500000,probability:30,status:'draft',deadline:offset(now,22),note:''}];d.events=[{id:'e1',title:'Follow-up penawaran',date:offset(now,1),time:'10:00',reminder:30,note:'',done:false},{id:'e2',title:'Review keuangan mingguan',date:offset(now,3),time:'19:00',reminder:15,note:'',done:false}];return d}
